application: sangiin-votes
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /job/(.*)
  script: job\1.py
  login: admin
- url: /admin/(.*)
  script: admin\1.py
  login: admin
- url: /list/(.*)
  script: list\1.py
- url: /
  script: listsessall.py
